# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/order_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 550)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(120, 40, 411, 471))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.status_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.status_label.setObjectName("status_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.status_label)
        self.reg_date_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.reg_date_label.setObjectName("reg_date_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.reg_date_label)
        self.client_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.client_label.setObjectName("client_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.client_label)
        self.compl_date_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.compl_date_label.setObjectName("compl_date_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.compl_date_label)
        self.status = QtWidgets.QComboBox(self.formLayoutWidget)
        self.status.setObjectName("status")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.status)
        self.reg_date = QtWidgets.QCalendarWidget(self.formLayoutWidget)
        self.reg_date.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.reg_date.setFont(font)
        self.reg_date.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.reg_date.setObjectName("reg_date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.reg_date)
        self.compl_date = QtWidgets.QCalendarWidget(self.formLayoutWidget)
        self.compl_date.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setKerning(False)
        self.compl_date.setFont(font)
        self.compl_date.setGridVisible(False)
        self.compl_date.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.compl_date.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.compl_date.setObjectName("compl_date")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.compl_date)
        self.client = QtWidgets.QComboBox(self.formLayoutWidget)
        self.client.setObjectName("client")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.client)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.table = QtWidgets.QTableWidget(self.formLayoutWidget)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.table)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.status_label.setText(_translate("Form", "Статус"))
        self.reg_date_label.setText(_translate("Form", "Дата регистрации заказа"))
        self.client_label.setText(_translate("Form", "Клиент"))
        self.compl_date_label.setText(_translate("Form", "Дата выполнения"))
