# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/puzzle_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 547)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(130, 209, 391, 162))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.puzzle_count_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.puzzle_count_label.setObjectName("puzzle_count_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.puzzle_count_label)
        self.design_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.design_label.setObjectName("design_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.design_label)
        self.wood_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.wood_label.setObjectName("wood_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.wood_label)
        self.puzzle_name_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.puzzle_name_label.setObjectName("puzzle_name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.puzzle_name_label)
        self.wood = QtWidgets.QComboBox(self.formLayoutWidget)
        self.wood.setObjectName("wood")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wood)
        self.puzzle_count = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.puzzle_count.setObjectName("puzzle_count")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.puzzle_count)
        self.puzzle_name = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.puzzle_name.setPlainText("")
        self.puzzle_name.setObjectName("puzzle_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.puzzle_name)
        self.desing = QtWidgets.QLabel(self.formLayoutWidget)
        self.desing.setText("")
        self.desing.setObjectName("desing")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.desing)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.puzzle_count_label.setText(_translate("Form", "Количество деталей, шт"))
        self.design_label.setText(_translate("Form", "Макет"))
        self.wood_label.setText(_translate("Form", "Фанерный лист"))
        self.puzzle_name_label.setText(_translate("Form", "Название пазла"))
